apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-server
resources:
  - namespace.yaml
  - radarr.yaml
  - sonarr.yaml
  - prowlarr.yaml
  - qbittorrent.yaml
  - seerr.yaml
  - profilarr.yaml
  - cleanuparr.yaml
  - huntarr.yaml
  - nzbget.yaml
