- Ingress:
    - Caddy:
        widgets:
          - type: caddy
            url: http://192.168.200.7:2019

- Monitoring:
    - Grafana:
        widget:
          type: grafana
          # version: 1 # optional, default is 1
          # alerts: alertmanager # optional, default is grafana
          url: http://grafana.monitoring:3000
          username: "{{HOMEPAGE_VAR_GRAFANA_USERNAME}}"
          password: "{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}"
    - Prometheus:
        widget:
          type: prometheus
          url: http://prometheus.monitoring:9090
- Media Server:
    - Seerr:
        href: https://seerr.brennonloveless.com
        widget:
          type: jellyseerr
          url: http://seerr.media-server:5055
          key: "{{HOMEPAGE_VAR_SEERR_API_KEY}}"
    - Jellyfin:
        href: https://jellyfin.brennonloveless.com
        widget:
          type: jellyfin
          url: http://jellyfin.jellyfin:8096
          key: "{{HOMEPAGE_VAR_JELLYFIN_API_KEY}}"
          enableBlocks: true # optional, defaults to false
          enableNowPlaying: true # optional, defaults to true
          enableUser: true # optional, defaults to false
          enableMediaControl: false # optional, defaults to true
          showEpisodeNumber: true # optional, defaults to false
          expandOneStreamToTwoRows: false # optional, defaults to true
    - Radarr:
        href: https://radarr.lan.brennonloveless.com
        widgets:
          - type: radarr
            url: http://radarr.media-server:7878
            key: "{{HOMEPAGE_VAR_RADARR_API_KEY}}"
            enableQueue: true
    - Sonarr:
        href: https://sonarr.lan.brennonloveless.com
        widgets:
          - type: sonarr
            url: http://sonarr.media-server:8989
            key: "{{HOMEPAGE_VAR_SONARR_API_KEY}}"
            enableQueue: true
    - Prowlarr:
        href: https://profilarr.lan.brennonloveless.com
        widget:
          type: prowlarr
          url: http://prowlarr.media-server:9696
          key: "{{HOMEPAGE_VAR_PROWLARR_API_KEY}}"
    - Qbittorrent:
        href: https://qbittorrent.lan.brennonloveless.com
        widget:
          type: qbittorrent
          url: http://qbittorrent.media-server:8080
          enableLeechProgress: true # optional, defaults to false
          enableLeechSize: true # optional, defaults to false

- Processing:
    - Fileflows:
        href: https://fileflows.lan.brennonloveless.com
        widgets:
          - type: fileflows
            url: http://fileflows.fileflows:5000
