title: "Brennons Homelab"

background:
  image: /images/firewatch-purple.png
  # blur: sm
  # saturate: 50
  # brightness: 50
  opacity: 15

layout:
  Ingress:
    style: row
    columns: 1
  Monitoring:
    style: row
    columns: 2
  Media Server:
    style: row
    columns: 3
  Processing:
    style: row
    columns: 1
