apiVersion: apps/v1
kind: Deployment
metadata:
  name: brennonloveless
  labels:
    app: brennonloveless
    component: server
spec:
  selector:
    matchLabels:
      app: brennonloveless
      component: server
  template:
    metadata:
      labels:
        app: brennonloveless
        component: server
    spec:
      containers:
        - name: brennonloveless
          image: bloveless/brennonloveless-com:0.2.2
          ports:
            - name: http
              containerPort: 80
