- name: Kraken config
  hosts:
    - kraken
  become: true
  gather_facts: true
  tasks:
    - name: Create mount directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: 1000
        group: 1000
        mode: "0755"
      loop:
        - /mnt/media
        - /mnt/homelab
        - /mnt/backups

    - name: Mount homelab NFS volume
      ansible.posix.mount:
        src: 192.168.0.115:/volume1/homelab
        path: /mnt/homelab
        opts: rw,sync,hard
        state: mounted
        fstype: nfs

    - name: Mount media NFS volume
      ansible.posix.mount:
        src: 192.168.0.115:/volume1/media
        path: /mnt/media
        opts: rw,sync,hard
        state: mounted
        fstype: nfs

    - name: Mount backups NFS volume
      ansible.posix.mount:
        src: 192.168.0.115:/volume1/backups
        path: /mnt/backups
        opts: rw,sync,hard
        state: mounted
        fstype: nfs

    - name: Install packages
      apt:
        state: latest
        update_cache: true
        name:
          - incus
          - neovim
          - htop
          - intel-gpu-tools

    - name: Install incus backup volumes scripts
      ansible.builtin.copy:
        src: ./scripts/incus-backup-volumes.sh
        dest: /usr/local/bin/incus-backup-volumes.sh
        owner: root
        group: root
        mode: "0744"

    - name: Install incus backup instances scripts
      ansible.builtin.copy:
        src: ./scripts/incus-backup-instances.sh
        dest: /usr/local/bin/incus-backup-instances.sh
        owner: root
        group: root
        mode: "0744"

    - name: Backup incus instances nightly
      ansible.builtin.cron:
        name: backup incus instances
        hour: "2"
        minute: "23"
        user: root
        job: "/usr/local/bin/incus-backup-instances.sh"
        cron_file: incus-backups
      when: ansible_hostname == "kraken02"

    - name: Backup incus volumes nightly
      ansible.builtin.cron:
        name: backup incus volumes
        hour: "3"
        minute: "32"
        user: root
        job: "/usr/local/bin/incus-backup-volumes.sh"
        cron_file: incus-backups
      when: ansible_hostname == "kraken02"
