apiVersion: v1
kind: Service
metadata:
  name: fritzandandre
spec:
  type: LoadBalancer
  selector:
    app: fritzandandre
    component: server
  ports:
    - name: http
      port: 8081
      targetPort: 8080
